#!/bin/sh
set -e

# Emptying some directories
for instance_dir in `ls -d /var/lib/apacheds-${app.version}/*`; do
  # Get instance and use it to shutdown
  instance=`echo $instance_dir | sed -e 's/.*apacheds.*\///g'`
  echo Shutting down ApacheDS instance $instance
  /etc/init.d/apacheds-${app.version}-$instance stop

  # Remove init script links
  rm /etc/rc0.d/K99apacheds-${app.version}-default
  rm /etc/rc3.d/S99apacheds-${app.version}-default

  # Backup old instance folders before deleting them
  timestamp=`date '+%Y%m%d_%H%M%S'`
  parent_dir=/var/lib
  tarball=$parent_dir/apacheds-${app.version}-$instance"_"$timestamp.tar
  echo Backing up old $instance instance data to $tarball
  tar cf $tarball $instance_dir
  gzip -9 $tarball
  rm -rf $instance_dir/partitions/*
  rm -rf $instance_dir/log/*
done
 
rm -rf /opt/apacheds-${app.version}/bin/wrapper.log
